# Preâmbulo Geral

project:
  type: book
  output-dir: docs

book:
  title: "**ESTATÍSTICA MUNICIPAL**"
  reader-mode: true
  subtitle: "**Perfil de Belém**"
  date: "29/02/2024"
  author:
  - name: "**Mário Diego Rocha Valente**"
    orcid: 0000-0001-7262-3336
  - name: "**Romildo Francelino de Oliveira**"
    orcid: 0000-0003-1725-3664
    corresponding: true

  page-footer:
    left: |
      Copyright: FAPESPA - 2024
    right: |
      Construído <a href="https://quarto.org/">Pacote Quarto no R4.3</a>.
  cover-image: Capa_Belem.jpg
  favicon: Capa_Belem.jpg
  site-url: https://www.fapespa.pa.gov.br/
  repo-url : https://github.com/MarioDhiego/Estatistica_Municipal_Fapespa_Belem
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Capitulo3.qmd
comments:
  hypothesis: true
bibliography: references.bib
format:
  html:
    theme:
      light: [blue,custom.scss]
      dark:  [cyborg,custom.scss]
    code-link: true
    toc-title: Índice
    toc-location: right


