
```{=html}
<style>
body{text-align: justify}
</style>
```


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


# Aspectos Históricos e Culturais
## Histórico

Na época da conquista do Pará, Espanha e Portugal, formavam a União Ibérica (desde 1580). Essa união fora motivada pela morte do rei-cardeal D. Henrique. Assumiu o trono português o rei espanhol D. Felipe II, neto de D. Manuel, o Venturoso. Para o Brasil, naquela fase de expansão territorial, a união peninsular foi benéfica, pois veio tornar sem efeito o Tratado de Tordesilhas, facilitando, desse modo, a penetração interiorana.

A conquista do Norte foi determinada pelo rei da Espanha e Portugal, D. Manuel. Visava, inicialmente, desalojar do Maranhão os franceses que ali haviam criado a França Equinocial. E, em 1614, Jerônimo de Albuquerque seguiu à frente da tropa, para cumprir aquela missão. A vitória definitiva sobre os franceses deu-se em 2 de dezembro de 1615, já com Alexandre Moura liderando as forças lusas desde outubro. Após essa vitória, Moura nomeou Jerônimo de Albuquerque governador do Maranhão e encarregou Francisco Caldeira Castelo Branco de conquistar o Pará.

No dia 25 de dezembro de 1615, a expedição saiu da Baía de São Marcos, composta do patacho Santa Maria da Candelária, da caravela Santa Maria das Graças e da Lancha Assunção. Compunha-se de 150 homens, 10 peças de artilharia, pólvora, muita munição e mantimentos. No dia 12 de janeiro de 1616, após transpor a barra do Separará, os portugueses aportaram na Baía de Guajará, chamada pelos nativos de Paraná-Guaçu.

Primitivamente, Belém (Mairi para os indígenas) era habitada pelos Tupinambás. O cacique chamava-
se Guaimiaba (cabelo de velha). Como não demonstraram hostilidade, os lusos mantiveram contato com os índios, foram para a terra e ali se estabeleceram. À nova conquista, Castelo Branco deu o nome de Feliz Lusitânia, colocando-a sobre a proteção de Nossa Senhora de Belém, e o engenheiro-mor Francisco Frias Mesquita iniciou a construção da Casa Forte, localizada num pequeno promotório à margem esquerda do rio Piry (hoje doca do Ver-o-Peso). Recebeu a denominação de Forte do Presépio (hoje Forte do Castelo) e em seu interior levantaram uma pequena capela, sob a invocação de Nossa Senhora das Graças.

Na tropa de Castelo Branco se encontrava Pedro Teixeira, cujo nome está ligado à exploração do
Amazonas, que foi encarregado de ir, por terra, a São Luís do Maranhão levar as boas novas.
Terminada a construção do Forte do Presépio, o próximo passo dos portugueses foi a colonização de
Belém. Ergueram as primeiras casas; os índios ajudavam, mas não demorou muito para que os brancos os
escravizassem.

No dia 7 de janeiro de 1619, os Tupinambás se revoltaram contra o regime de escravidão que os
brancos lhe impunham e muitas tribos não se conformavam em ceder suas terras aos estrangeiros. As lutas
contra os nativos se alastraram, movidas pelo interesse de ganhar dinheiro escravizando os indígenas.

Além destas, os portugueses também se envolveram na luta contra os estrangeiros, para evitar que os
franceses, ingleses e holandeses dominassem o vale amazônico, onde já haviam construído várias fortalezas.
Vencidas as lutas com os índios Tupinambás e Pacajás e com os invasores estrangeiros holandeses, ingleses e
franceses, a cidade perdera a primitiva denominação de “Feliz Lusitânia”, passando a ser “Nossa Senhora de
Belém do Grão Pará”, para a qual Felipe da Espanha concedera foros de capitania.
Importante sob todos os aspectos foi a ação dos religiosos na conquista espiritual da Amazônia.
Com Castelo Branco, veio o padre Manoel Figueiredo de Mendonça, que realizou a primeira missa em
Belém e que depois foi nomeado o primeiro vigário do Pará.

Belém nasceu com foros de cidade, porém a data e o ato de criação desse Município perderam-se na
deficiência dos documentos, como também ficaram esquecidos os nomes do primeiro Presidente e demais
autoridades que integraram a fase inicial da administração municipal. Contudo, relata Palma Muniz, há claros
indícios da existência de um Senado da Câmara, a partir de 1625, visto que este teria adotado decisões
enérgicas sobre o magno problema dos índios, então apaixonadamente debatido e controvertido, como, por
exemplo, a representação interposta contra a pastoral de Frei Cristóvão de São José, em 21 de dezembro do
mesmo ano, com relação à administração das aldeias indígenas. Em 1636, prossegue o mesmo autor, surgem
os primeiros registros da história geral do Pará, no meio das agitações decorrentes da sucessão do governo da
Capitania. Na ocasião, o Senado da Câmara emprestou decisivo apoio ao reconhecimento de Jacome Raimundo
de Noronha como Capitão General, contra os veementes protestos do vereador Luís do Rego, que em atitude
considerada incompatível com o absolutismo da época, declarou não reconhecer ao Senado da Câmara de São
Luís do Maranhão competência para nomear o Capitão General do Pará. Todos esses fatos, conclui Muniz,
denotam que o Senado da Câmara já era uma corporação que intervinha na vida geral da Capitania e tinha foro
de existência respeitada.

Desconhece-se o local onde primitivamente funcionou o Senado. Documentos relatam que teria sido em
uma casa localizada na esquina da Travessa da Rosa (atual Félix Rocque) com a Rua do Norte (atual Siqueira
Mendes).

Em 1650, o Padre Antônio Vieira dizia em sua “Resposta aos Capítulos do Procurador do Maranhão”
que a população de Belém somava 80 almas, sem incluir os nativos, os religiosos e os soldados. As primeiras
ruas foram abertas, todas paralelas ao rio. Os caminhos transversais levavam ao interior. Era maior o
desenvolvimento para o lado norte, onde os colonos levantaram suas casas de taipa, dando começo à
construção do bairro que hoje é conhecido como Cidade Velha.

Até meados do século XVII, Belém possuía, além dessa construção, a Santa Casa de Misericórdia,
fundada em 24 de fevereiro de 1619; o Convento de Santo Antonio, fundado em 1626; a igreja e o Convento de
Nossa Senhora das Mercês, construídos em 1640, pelos mercedários Frei Pedro da La Cirne e Frei João da
Mercê, e onde, em 1796, D. Francisco de Sousa Coutinho mandou instalar a Alfândega, e lá ainda continua; a
igreja de Nossa Senhora do Carmo; as obras da Ordem dos Carmelitas Calçados, no local onde Bento Maciel
possuíra uma casa de resistência; e a igreja de São Francisco Xavier (atual Santo Alexandre), inaugurada pelos
jesuítas em 1660.


O ano de 1655 talvez tenha sido a data da elevação de Belém à categoria de cidade, em conformidade
com o Ofício, de 29 de abril de 1733, existente no Arquivo Público do Pará. Neste documento, os oficiais da
Câmara comunicaram ao Governo da Capitania que “Sua Majestade nos fez mercê há setenta e oito anos
(1655), conceder-nos os mesmos privilégios que gozam os cidadãos da cidade do Porto, do que mandou passar
Provisão”.

A mais antiga vereação da Câmara de que se tem notícia, pelos manuscritos conhecidos é a de 1661,
constituída pelos vereadores: Bernardino de Carvalho, Manoel Álvares da Cunha, Gaspar da Rocha Porto
Carneiro, Braz da Silva e Manoel Braz.

Absorvidos os portugueses com domínio da região amazônica, além de frequentes conflitos com índios
e estrangeiros, não lhes foi possível cuidar, nos tempos iniciais, do progresso da Capitania. O móvel maior - a ambição do ouro - era a causa principal dessa estagnação que, apesar do meio século de permanência, dava à
Colônia a orientação dos primeiros dias. A ideia da fortuna imediata toldava todos os espíritos, sem distinção de crenças ou de cargos, e a cidade teve que sofrer as consequências das ambições de seus primeiros
colonizadores. Em 1676, chegaram da Ilha dos Açores 50 famílias, no total de 234 pessoas. Eram agricultores
que o Senado da Câmara localizou no trecho conhecido como Rua São Vicente, atual Manoel Barata.

O mais antigo livro de atas do Senado da Câmara de Belém data de 1713, quando serviram como
juízes ordinários André de Oliveira Pinto e Pedro de Seixas Borges.

No século XVIII, a cidade começou a avançar para a mata, ganhando distância do litoral.

Em 1667, foi criado o Bispado do Maranhão. As cartas régias de 1693 e1694 distribuíram o litoral e o
interior pelas ordens religiosas que atuavam na Amazônia: jesuítas, mercedários, frades de Santo Antônio,
carmelitas e os frades da Piedade. No dia 4 de março de 1719, o papa Clemente IX, através da Bula Copiosus in
Misericórdia, criou o Bispado do Grão-Pará, sendo nomeado o seu 1o Bispo, D. Frei José Bartolomeu do Pilar, da
Ordem dos Carmelitas Calçados. D. Romualdo de Souza Coelho, empossado em julho de 1821, se achava à
frente do bispado quando o Pará aderiu à Independência do Brasil. A população era de 6.574 “almas”.

Em 1673, o governador Pedro César de Menezes transferiu a sede da capitania do Grão-Pará e
Maranhão (unificadas em um só Estado, desde 1623) de São Luis para Belém. Em 1688, a corte determinou que
a capital voltasse a ser São Luis; mas em 1737 a sede governamental retornou a Belém. Finalmente, em 1815,
as Capitanias Gerais do Brasil foram transformadas em Províncias, ficando Belém como Capital da Província do
Grão-Pará.

A lei de 12 de junho de 1748 estabeleceu o derrame de moeda de metal-cobre, prata e ouro, para
substituir os novelos de algodão e os gêneros nativos utilizados como valor de troca na época. Por requerimento dos habitantes, foi fundada, em 1755, a Companhia de Comércio, que durou 22 anos e trouxe ao Pará 12.587 escravos africanos, dos quais muitos foram vendidos para Mato Grosso, por falta de compradores locais.
A construção do Palácio do Governo, cuja planta é de autoria do arquiteto Antônio José Landi, foi
concluída em 1771.


Em 1793, D. Francisco de Sousa Coutinho, Capitão-General do Grão-Pará e Rio Negro, organizou o
Círio de Nossa Senhora de Nazaré, tradicional préstito religioso que movimenta todo o Estado. A imagem da
santa é venerada pelos paraenses desde 1700.

Foram estabelecidos os serviços de Correios, de serventia pública, de abertura de novos logradouros,
além de se criarem escolas de ensino primário e de humanidades. As tropas militares ficaram agrupadas em
uma imensa casa térrea que se estendia da Travessa São Francisco à de São Pedro e que deu origem ao nome
de Largo dos Quartéis, hoje Praça da Bandeira. Ao terminar o ano de 1799, a cidade contava com 1.083 “fogos” (casas) e 10.620 habitantes. Dom Francisco de Sousa Coutinho, cavaleiro da Ordem de Malta, Capitão-de-
Fragata da Real Armada Portuguesa, era o governador e Capitão-General do Grão-Pará e Rio Negro.

A retirada de Dom João VI para Portugal e os acontecimentos que dominavam o cenário no Brasil,
relativos ao regime constitucional, passaram a repercutir em Belém, criando situações novas para a cidade e,
sobretudo, para a vida política municipal. A mais importante dessas circunstâncias foi, sem dúvida, a adesão do
Pará à Independência. O Senado da Câmara, constituído em 1823 e empossado em 27 de fevereiro, sofreu
decisiva influência na sua composição por parte da Junta Provisória do Governo Civil da Província do Pará.
Porém, a deposição dessa junta governativa pelo Coronel João Pereira Vilaça, em 1o de março de 1823, trouxe
como consequência a distribuição desse Senado. Entretanto, os líderes paraenses que trabalhavam pela
Independência e que realizaram a adesão do Pará em 15 de agosto empossaram o dito Senado. Assim, a
primeira Câmara de Belém, composta depois de decretada a Independência do Brasil, foi presidida por Pedro
Rodrigues Henriques e instalada, solenemente, em 23 de agosto pela Junta Provisória do Governo do Pará,
integrada por Geraldo de Abreu, João Batista Gonçalves Campos e Félix Antônio Clemente Malcher.


A Lei-Geral de Organização Municipal do Império, de 1o de outubro de 1828, estabeleceu para todos os
Municípios brasileiros a eleição direta para a composição de seus respectivos corpos deliberativos. No ano
seguinte, em 6 de julho, tomou posse em Belém a primeira Câmara Municipal eleita, da qual fizeram parte o
Comendador Ambrósio Henrique da Silva Pombo, na qualidade de presidente, e os vereadores Coronel Manoel
Sebastião de Mello Marinho Falcão, Tenente-Coronel Lourenço Lucidoro da Motta, Capitão José Batista
Camecran, Capitão Joaquim Antônio da Silva, Tenente João Batista Ledo, Capitão Antônio Manoel de Sousa
Trovão, João Florêncio Mendes Cardoso e Capitão Pedro Carlos Damasceno.

Em consequência das lutas deflagradas pelo movimento da Cabanagem, a Câmara Municipal de Belém
sofreu várias alterações. O Presidente da Câmara, Antônio Manoel de Sousa Trovão, foi preso e os vereadores
fugiram da Capital, sendo chamados seus suplentes, entre os quais João Antônio Corrêa Bulhão, que sucedeu a
Trovão na presidência da Câmara.

A Cabanagem foi um movimento popular cujo objetivo era a tomada do poder das elites portuguesas,
que governavam a Província do Grão-Pará. Foi liderado intelectualmente pelo Cônego Batista Campos, que
dirigia o jornal “O Paraense” e fazia oposição aos atos do governo, e, bélica e estrategicamente, pelos irmãos
Francisco e Antônio Vinagre, além de Eduardo Angelim.

No dia 4 de dezembro de 1833, assumia a Presidência da Província do Pará, em substituição a
Machado de Oliveira, o brigadeiro Bernardo Lobo de Souza. O novo Presidente incidiu no erro de inimizar-se
com Batista Campos. Após vários incidentes ocorridos, Batista Campos, perseguido pelo governo, veio a falecer
em 31 de dezembro de 1843. Assim que a notícia se espalhou, a culpa pela morte (em decorrência de um tumor
maligno) foi atribuída aos governantes. Revoltados, os lideres cabanos passaram então a recrutar os caboclos
para a invasão da cidade de Belém, sede da Província, e para a tomada do poder, o que ocorreu no dia 7 de
janeiro de 1835, quando mataram várias autoridades do governo, entre elas o Presidente da Província. Após o
assassinato do presidente Lobo de Sousa, a Câmara passou a constituir um baluarte contra os cabanos, embora
mantivesse um comportamento de relativa tolerância, para evitar maiores desgraças e aguardar o apoio do
governo imperial no restabelecimento do regime da legalidade.

Além das lutas sucessivas durante o período cabano, houve também, a crise econômico-financeira.
Assim, quando forças legais tomaram conta da cidade, em maio de 1836, encontraram uma Belém cheia de
carcaças de edifícios, sem iluminação pública, em uma decadência quase total. Andréa, o novo Presidente da
Província, tentou melhorar as coisas. Com a expansão da cidade, os problemas se avolumaram. Um dos
maiores problemas que enfrentou foi o dos terrenos alagadiços e a falta de operários especializados.

A partir de então, e por longos anos, novos conflitos e mortes se sucederam com vários cabanos
assumindo por algum tempo a presidência da Província, entre eles, Francisco Vinagre, então com 19 anos e
Eduardo Angelim, com 21. Antônio Vinagre era mais jovem e morreu em batalha em agosto de 1835.
Finalmente, devido à ausência de um líder com o conhecimento de Batista Campos, o movimento revolucionário,
não muito consistente, foi debelado de vez em 1840 pelas forças do Marechal José Soares de Andréa, novo
Presidente da Província, nomeado pela regência, depois de muito sangue derramado, mas que marcou a história
do Pará.

Quando da Cabanagem, Belém pouco se diferençava daquela pequena urbe do final do período
colonial; restringia-se aos bairros da Cidade e da Campina, com o igarapé Piri dividindo-os. O bairro de Nazaré
era um bosque imenso. Ligando o largo onde se erguia a modesta ermida de Nossa Senhora de Nazaré, havia
uma estrada, chamada de Nazaré. Não houve nenhuma modificação urbanística para melhor; para pior muitas,
em decorrência das lutas e dos bombardeios de que a cidade foi vítima.

Em 1844, assumiu outro presidente, Conselheiro Jerônimo Francisco Coelho, que foi o maior
administrador do período imperial. Considerando o período e as condições, pode ser comparado ao de
Mendonça Furtado, no período colonial, e ao de Antonio Lemos, na fase republicana. Executou muitas obras e
planejou outras tantas que, por falta de recursos não puderam ser realizadas. Mas, o que é importante, deixou
um plano urbanístico para uma cidade cheia de problemas.

Mais de duzentas publicações, entre jornais, revistas e panfletos, circularam por Belém na época do
Império, algo surpreendente para uma cidade pequena e isolada dos grandes centros. A imprensa em Belém e
na Amazônia foi introduzida por Felipe Patroni, Domingos Simões da Cunha e José Batista da Silva, em 1822
quando fundaram o jornal “O Paraense”, à época em que ainda éramos subordinados ao governo português.
Sua tipografia serviu para imprimir o primeiro jornal que circulou em Belém, já após a sua integração ao Império
do Brasil: O Independente, semanário cujo primeiro número foi lançado em 8 de dezembro de 1823, redigido
pelo padre João Lourenço de Souza, defendia uma facção exaltada da política paraense. O governo passou a

editar “O Verdadeiro Independente”, semanário cujo primeiro número saiu em agosto de 1824. Seu primeiro
redator foi D. Romualdo de Seixas. Outros exemplos da imprensa na época do Império são: “O Estado”; “O
Treze de Maio”, primeiro jornal diário do Estado (que leva este nome em homenagem à data em que as forças
legalistas retomaram Belém); e o “Diário de Notícias”.

Em 1831, surgiu um jornal que muito influiu na agitada política paraense e antecedeu à explosão da
Cabanagem: Orpheo Paraense. O Cônego Batista Campos foi encarregado de sua redação e imediatamente o
transformou em porta voz de suas ideias nacionalistas exaltadas, ajudado pelos padres Jerônimo Pimentel e
Gaspar de Sequeira Queiroz. Além deste, Batista Campos publicou vários semanários e jornais. Para fazer
frente à linha exaltada de Batista Campos, vários jornais circularam, entre eles: “A Opinião”, “O Despertador” e
“Correio Oficial Paraense”, que circulou de julho de 1834 até janeiro de 1935, fundado pelo presidente Bernardo
Lobo de Souza. O antigo colaborador de Batista Campos redigia-o, o Cônego Gaspar de Sequeira Queiroz,
transformado agora em seu ferrenho adversário.

Dessa tumultuada fase deve-se mencionar “A Sentinela Maranhense na Guarita do Pará”, de Batista
Campos e redigido por Vicente Lavor Papagaio, publicado em setembro e outubro de 1834, que acelerou o
processo cabano. Durante os governos revolucionários da Cabanagem, circularam apenas dois jornais de vidas
efêmeras: “Paquete do Governo” e “Publicador Oficial Paraense”. Após o ciclo cabano, a imprensa paraense
voltou a reviver por meio da “Folha Comercial do Pará”, semanário que circulou de agosto de 1837 a 1840.
Honório José dos Santos, figura de destaque na história da imprensa paraense, o redigia. Encerrou-a em 1840
para lançar o primeiro jornal de longa vida do período colonial: o “Treze de Maio”.

A Proclamação da República, em 15 de novembro de 1889, implicou na deposição do regime
monárquico, e a posse das autoridades republicanas no Pará foi realizada na Câmara Municipal de Belém. Para
isto, reuniu-se a Câmara, em sessão extraordinária, no dia 18 de novembro, sob a presidência de Antônio José

Lemos, perante a qual compareceram os membros do Governo Provisório do Pará, Dr. Justo Chermont, Capitão-
de-Fragata José Maria do Nascimento e Tenente-Coronel Bento José Fernandes Júnior, que prestaram

juramento e foram empossados no Governo do Estado Confederado do Pará. Em virtude da Vigência do novo
regime republicano, a Câmara Municipal de Belém foi extinta pelo Decreto Lei no 3, de 5 de dezembro de 1889 e,
pelo mesmo ato, foi criado o Conselho Municipal.

Com a Lei Orgânica dos Municípios, de 28 de outubro de 1891, os Municípios do Estado passaram a
ser governados por um Intendente Municipal, com funções executivas e um Conselho Municipal, com funções
deliberativas. Em consequência dessa Lei, tiveram lugar as primeiras eleições municipais do período republicano
no Pará, cujo mandato compreendeu o triênio de 1891 a 1894. Em 15 de novembro de 1891, tomaram posse os
eleitos: D. Gama Abreu (Barão de Marajó), como Intendente, e os Vogais Dr. José Antônio Pereira Guimarães,
José Marques Braga, Dr. Theodorico Cícero Ferreira Pena, Antônio Delfim da Silva Guimarães, Filadelfo de
Oliveira Condurú, Cícero da Costa Aguiar e Leônidas Ramiro da Silva Castro.

Durante os anos de 1897 a 1911, administrou Belém o Intendente Antônio José de Lemos, sendo
considerada esta época a fase áurea do Município. São atribuídos a esse período o embelezamento e
desenvolvimento da cidade. Os calçamentos de madeira foram substituídos pelos de granito. Foram construídos: o Mercado de Ferro; o Quartel dos Bombeiros; o Asilo de Mendicidade; o Necrotério Público; a rede de esgotos;
os largos foram transformados em praças ajardinadas; o bairro do Marco ganhou abertura de ruas e travessas.
Enfim, foram promovidos vários tipos de melhoramentos do perímetro urbano, inclusive tendo sido instalada a
iluminação pública com rede elétrica, a viação pública por bondes elétricos e surgiram dois grandes jornais
diários: “A Província do Pará” e a “Folha do Norte”, que refletiam o progresso da capital guajarina junto aos
suntuosos prédios e esplêndidas moradias que se construíram nessa época. Porém, a derrocada do ciclo da
borracha e a Primeira Guerra Mundial estancaram o crescimento da grande metrópole da Amazônia.

A Reforma da Constituição do Estado, promulgada em 3 de setembro de 1914, mudou a administração
do Município da Capital, pois ficou composta por um Conselho Municipal de 12 membros, eleito diretamente, e
por um Intendente Municipal, nomeado pelo Governador do Estado. O primeiro Intendente nomeado foi o Dr.
Antônio Martins Pinheiro, que tomou posse em 14 de setembro de 1914, e o Presidente eleito para o Conselho
Municipal foi Dr. Dionísio Auzier Bentes.

Após a vitória da Revolução de 1930, o primeiro Intendente de Belém foi o Dr. Ismael de Castro,
seguido do Dr. José Carneiro da Gama Malcher e Padre Leandro Pinheiro.

Com a reconstitucionalização de 1945, a Câmara de Vereadores de Belém ficou composta por Adolfo
Burgos Xavier, Lucival Lage Lobato, Francisco do Céu Ribeiro Sousa, Armando Dias Mendes, Benedito José de
Carvalho, Mário Chermont, Augusto Belchior de Araújo, Raimundo Farah, Antônio Carlos dos Santos e
Melquíades Teixeira Lima.

A Lei Federal no 1.645, de 16 de julho de 1952, devolveu o direito aos Municípios de eleger seus prefeitos, tendo
ocorrido a primeira eleição em Belém em 27 de setembro de 1953, da qual saiu vitorioso o Dr. Celso Carneiro da
Gama Malcher.

O golpe militar em 1964 resultou em nova suspensão dos direitos de livre escolha dos prefeitos das
capitais estaduais brasileiras. Porém, com o processo de redemocratização nacional, que teve início em 1985,
Belém elegeu, nesse ano, Fernando Coutinho Jorge como Prefeito da Capital Paraense.

A cidade fundada em 1616, como o nome de “Feliz Lusitânia”, depois denominada de “Nossa Senhora
de Belém do Grão Pará”, tradicionalmente conhecida como “Santa Maria de Belém do Grão Pará” agora,
simplesmente é designada Belém.

Do imenso patrimônio territorial de que Belém dispunha ainda nos primórdios do século, como por
exemplo, as áreas de Benfica, Barcarena, Santa Izabel, Apeú, Castanhal, Inhangapi, Inhanga (São Francisco do
Pará), Ananindeua etc., foram progressivamente sendo desmembradas de suas terras, para dar origem aos
Municípios homônimos. Atualmente, de acordo com a Lei Municipal no 7.682, de 5 de janeiro de 1994, o
município de Belém conta com os distritos administrativos de Belém (sede), Icoaraci, Mosqueiro, Benguí,
Entroncamento, Sacramenta, Guamá e Ilha de Caratateua (popularmente conhecida como Outeiro).

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

## Cultura
### Patrimônio Cultural
#### Festas Religiosas 
##### Círio de Nazaré

A maior manifestação religiosa do município de Belém e uma das maiores do Brasil é o Círio de Nossa
Senhora de Nazaré, considerado o "Natal do paraense" e realizado no segundo domingo de outubro.
As comemorações do Círio começam 30 dias antes, com a celebração da Missa do Mandato, pelo
arcebispo metropolitano, que dá início às peregrinações de Nossa Senhora, quando as réplicas das imagens
percorrem todos os bairros de Belém de casa em casa com novenas noturnas. Nesse período, as famílias
católicas reúnem-se diariamente com os vizinhos para rezar o terço e refletir sobre diversos temas, em
preparação espiritual para a grande festa.

A partir da sexta-feira, antevéspera do Círio, começam as grandes homenagens a Nossa Senhora de
Nazaré. A primeira delas é a Rodo-Romaria, que, seguida por carros e caminhões enfeitados, leva a imagem do
Colégio Gentil Bittencourt até Ananindeua. No sábado de manhã cedo, a imagem é levada até a Vila de Icoaraci.
De lá, segue em romaria fluvial, desde 1986, com centenas de embarcações, até a Praça Pedro Teixeira em
Belém.

Assim que chega, a pequena imagem é conduzida em veículo especial e seguida por uma Moto-
Romaria, que a leva de volta ao Colégio Gentil Bittencourt.

No sábado à noite, a partir das 19 horas, começa a Trasladação. A berlinda com a imagem de Nossa
Senhora de Nazaré é levada até a Catedral da Sé, fazendo o trajeto contrário do Círio. No domingo de manhã, a
procissão leva pequena imagem da Virgem de Nazaré, ornamentada com flores, pelas ruas da cidade na grande
procissão em direção à Basílica de Nazaré, cumprindo um ritual de mais de 200 anos. A berlinda é puxada por
uma grossa corda, que os romeiros, em grande sacrifício, vão segurando como pagamento de promessa, do
início ao fim da procissão.

O Círio atrai milhares de devotos que vêm à romaria agradecer por uma graça alcançada. Simbolizando
isso, levam na cabeça casas, barcos, pedaços do corpo em cera e os mais variados objetos que representam o
que teriam conseguido com a fé à Virgem.

Os romeiros e promesseiros vêm de todos os cantos do interior do Pará e de outros Estados, o que
confirma a tradição de uma das maiores manifestações de fé do Brasil.

Ao chegar à Praça Santuário, que fica bem em frente à Basílica, é rezada uma missa pelo arcebispo de
Belém, onde todos os devotos da Virgem de Nazaré são abençoados.

Quando a procissão termina, as famílias se reúnem para o tradicional almoço do Círio, no qual são
servidos pratos típicos como o pato no tucupi e a maniçoba.

A festa na Basílica segue por duas semanas, com visitas à imagem e ao Parque de Diversões, ao lado
do Conjunto Arquitetônico de Nazaré.

Durante a quadra Nazarena, ainda é realizado o Círio das Crianças e a Corrida do Círio, evento que
reúne corredores de diversas partes do Estado e do Brasil.

Quinze dias depois, acontece o "Recírio", que leva a imagem da Basílica de volta até o Colégio Gentil
Bittencourt, de onde só sai no ano seguinte.

##### Festividade de Nossa Senhora de Belém

Outra manifestação religiosa que pode ser destacada é a festa em homenagem à padroeira oficial da
cidade, Nossa Senhora de Belém, cultuada no dia 1o de setembro, a partir das heranças religiosas deixadas
pelos portugueses. As festividades contam com procissão, novena e arraial em torno da igreja matriz.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### Formação Étnica

A herança étnica da população de Belém é uma mistura de traços do branco europeu, do negro e,
sobretudo, do índio – características que lhe dão o apelido de “Cidade Morena”. Hoje, a cidade não é só a capital
dos paraenses, mas também de imigrantes, em especial nordestinos. Aliás, a herança desses povos também
tem outras manifestações, seja nos costumes ou na forma de se expressar, revelando as raízes e um mundo
fantástico de danças, comidas, artesanatos e lendas ou nos antigos casarões, palacetes e igrejas que fazem do
bairro da Cidade Velha uma espécie de museu a céu aberto.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### Folclore

O folclore é uma das manifestações mais ricas da cultura popular do belemense e é de uma
expressividade autêntica. Entre as manifestações culturais mais apreciadas estão os Folguedos Populares. Em
junho, os Cordões de Pássaros, os Bois-Bumbás, as Quadrilhas, as Pastorinhas e as festas de “arraiá”,
animadas pelos conjuntos típicos ou pelo sonoro “arrebenta-quarteirão” que, sacudidas pelos rojões e foguetes,
esquentam as noites. Em julho, as festas transferem-se para as praias mais próximas, já que é o grande mês de
férias do paraense. Nos finais de semana, os sonoros tomam conta da cidade, e, dividindo espaço com os
espetáculos de cantores e músicos paraenses, shows de Carimbó (com destaque para o Mestre Verequete e
Pinduca) e Brega. 

Em se tratando de Folguedos Populares, o Boi-Bumbá é um folguedo que, na opinião do folclorista
Carlos Lima, é tipicamente paraense. É o resultado da mistura bonita das três raças – a indumentária do branco,
o atabaque do negro e a coreografia do índio. Conta-se que, na Belém da segunda metade do século XIX, o Boi-
Bumbá reunia negros e escravos em um folguedo que misturava, ao ritmo forte, a representação de um motivo
surpreendente para a época: a luta de classes dentro da sociedade colonial. Apesar da repressão, o boi tornou-
se uma das mais importantes representações da cultura local. A seguir, alguns dos grupos de Bois-Bumbás
encontrados em Belém: Boi-Bumbá “Pai da Malhada” (fundado em 1935), Boi-Bumbá “Caprichoso” (1947), Boi-
Bumbá “Tira Fama” (1958), Boi-Bumbá “Flor do Campo” (1960), Boi-Bumbá “Estrela D’alva” (1963), Boi-Bumbá
“Pingo de Ouro”(1969), Boi-Bumbá “Flor do Guamá”(1975), Boi-Bumbá “Flor da Noite”(1982), Boi Malhadinho
Mirim do Guamá. Um dos mais importantes personagens ligados à história do Boi-Bumbá morreu em 1997. 

Elias Ribeiro da Silva, o “seu Setenta”, durante mais de 40 anos zelou pela manutenção do boi em Belém. O Arraial do
Pavulagem é um dos grupos mais famosos do Estado. Ele foi peça importante no resgate do Boi-Bumbá em uma
época em que o folclore não estava em alta entre os jovens. O Arraial do Pavulagem se apresenta durante a
quadra nazarena, promovendo o “Arrastão do Círio”, que sai da Igreja da Sé em direção à Praça do Carmo, após
a romaria fluvial.

As Quadrilhas Juninas, de origem portuguesa, são centenas em todo o estado. Hoje, as quadrilhas
são tão importantes para a cultura, que a Prefeitura de Belém organiza um festival anual muito concorrido; um
dos eventos mais esperados da cidade. Na capital paraense existem cerca de 120 quadrilhas organizadas, que
cada vez mais se aprimoram em coreografias criativas.

Os “Cordões de Pássaros” constituem uma espécie de opereta cabocla e só existe no folclore
paraense. Provavelmente, o primeiro pássaro junino surgiu em 1877, no então Largo de Nazaré, hoje Centro
Arquitetônico de Nazaré. Apesar de serem chamados de Pássaros, esses grupos de teatro dramático-burlesco-
popular nem sempre usam as aves como seu símbolo. A riqueza da indumentária é motivo de orgulho para os

organizadores dos Pássaros. Na verdade, tanto o Boi-Bumbá como o Cordão de Pássaros representam entidades que surgem como forma de resistência da cultura regional. Grande parte desta cultura é transmitida de geração em geração,
apenas pela tradição oral. O engendrar de cultura e resistência garante a autenticidade dessa autêntica
manifestação.

O Carnaval é outra manifestação popular que movimenta a cidade. A primeira escola de samba de
Belém (e do Pará) surgiu em 1934, o “Rancho Não Posso Me Amofiná”. Na década de 70 e 80, foram
organizadas batalhas de confete promovidas por algumas emissoras de rádio da cidade (Rádios Clube do Pará,
Marajoara e Liberal). Atualmente, a Prefeitura de Belém realiza desfile das escolas de samba que são
classificadas por grupos. As escolas de samba que se destacam no carnaval belenense são: Rancho
Carnavalesco Não Posso Me Amofiná (fundado em 1934), Império de Samba Quem São Eles (1946),
Acadêmicos da Pedreira (1981), Embaixada de Samba Império Pedreirense (1958), Associação Carnavalesca a
“Grande Família” (1973), Escola de Samba da Matinha, Academia de Samba Jurunense. Segundo o professor
Georgenor Franco, o primeiro Rei Momo foi Kagib Elias Eluan, mas o mais famoso de Belém (e do Pará) foi
Mário Cuia, falecido em 1975. Também se tornou tradição o concurso “Rainha das Rainhas do Carnaval
Paraense”, que envolve os principais clubes sociais de Belém, idealizado pelos jornalistas do extinto jornal Folha
do Norte, João Maranhão e Ossian Brito, em 1947.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### Gastronomia

A culinária paraense é considerada uma das mais típicas e variadas do Brasil. É uma culinária
exuberante. Os pratos típicos utilizam produtos naturais, colhidos das fontes mais puras encontradas na flora e
na fauna amazônicas, sem similar em outro lugar do mundo, sendo essa, uma forte herança deixada pelos
índios da região. O grande logotipo da gastronomia do estado é o pato no tucupi. Outra iguaria típica é a
maniçoba, conhecida como a “feijoada do paraense”. A variedade de peixes que povoam os rios da região é responsável pela diversidade de pratos de frutos da água como: pirarucu, pirarucu grelhado ou na brasa,
pirarucu no leite de coco, desfiado de pirarucu, peixada, caldeirada, tamuatá no tucupi. Há, também, as iguarias
feitas com crustáceos: casquinha de caranguejo, unha de caranguejo, caranguejo toc-toc.

Nas esquinas das principais ruas das cidades paraenses, sobretudo em Belém, há bancas de tacacá
(tacacazeiras). Além do tacacá em si, vendem também outras iguarias da culinária regional, como o vatapá e o
caruru paraenses, constituindo-se, na maioria das vezes, uma refeição completa, hábito bastante cultivado pela
população local.

Com mais de uma centena de espécies comestíveis, as frutas regionais podem ser encontradas no Ver-
o-Peso, mercados, supermercados etc., da cidade de Belém. Elas são as responsáveis diretas pelo indefinível,
requintado e muitas vezes exótico sabor das deliciosas sobremesas que enriquecem a mesa paraense.
Destacam-se: açaí, bacaba, cupuaçu, castanha-do-Pará, bacuri, pupunha, tucumã, muruci, piquiá e taperebá.

O açaí, popularizado em todo país como um energético, também é vendido em centenas de
barraquinhas de rua, assinaladas com uma bandeira vermelha na qual está escrito o nome do produto. Muitas
pessoas têm o hábito de consumir o açaí como uma refeição completa, puro ou guarnecido com camarão
salgado e outros.

Além dos sorvetes, refrescos, pudins, tortas, cremes, licores, compotas, mousses e balas, pode-se
ainda encontrar em Belém outras delícias de confecção artesanal e sabor caseiro, como: beijo de moça,
munguzá ou mingau de milho, beiju de mandioca, mingau de banana verde, tapioquinha, mingau de açaí,
mingau de bacaba e tantas coisas mais.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### Artesanato

O artesanato de Belém é expressivo, pelo toque original e multicolorido. Apresenta grande variedade de
produtos, a exemplo de pequenos objetos de uso pessoal (colares, anéis etc.); utensílios caseiros e decorativos
(cerâmica, vasos, bacias etc.); além de outros artigos em couro de cobra e jacaré, em madeiras e fibras
regionais e em penas e barro, que podem ser encontrados no Ver-o-Peso ou, nos finais de semana, na Praça da
República. Entretanto, o destaque especial é dado às cerâmicas Marajoara (oriundas da Ilha do Marajó),
Tapajônica (encontrada na região do Tapajós – Santarém), Maracá (originária do Amapá) e cerâmica de Icoaraci
(estilizada, criada a partir das cerâmicas Marajoara e Tapajônica, permitindo maior uso doméstico), cultura
deixada como herança pelos índios e que hoje é fonte de renda para muitos moradores da Vila de Icoaraci, que
é o centro produtor do artesanato paraense, localizada a 20 Km de Belém.

Esses produtos são postos à venda na Feira do Paracury (inaugurada em 24 de junho de 1995, com a
finalidade de incentivar e escoar a produção de artesanato, assim como o de divulgar a cultura da terra –
danças, músicas e comidas típicas), onde se encontram barracas de vários artesãos da vila. Além do Liceu de
Artes e Ofícios e das lojas de artesanato da vila; outro local onde se encontram trabalhos de vários ceramistas é
a COARTI (Cooperativa dos Artesãos de Icoaraci), instalada em uma antiga estação de trem (Estrada de ferro
Belém-Bragança) e que foi criada para melhorar a qualidade da cerâmica produzida na vila, pois os artesãos não
estavam seguindo corretamente as técnicas milenares de confecção das peças, e para conscientizar a população a resgatar a cultura dos antigos povos da Amazônia, o que se constitui numa tarefa importante para a
sobrevivência da cerâmica e da economia local.

Na Rua dos Artesãos e na Passagem Livramento concentra-se o maior número de olarias da vila, de
onde saem as mais variadas peças do artesanato local (vasos, cinzeiros que podem ser personalizados, urnas,
pratos etc.) para o mercado. Nesses locais, a cerâmica pode ser adquirida a preço de custo, além de que se
pode acompanhar todo seu processo de produção.

Em termos de artesanato, também o antigo Presídio São José, localizado na Praça Amazonas, foi
reformado e sedia, atualmente, o Centro de Referência Joalheiro e Artesanato. O Projeto Jóias do Pará é uma
iniciativa do Governo do Estado, por meio da Secretaria Executiva do Trabalho e Promoção Social, em parceria
com Prefeituras Municipais, instituições Federais e o Setor Privado. O objetivo é incrementar a produção de jóias
do Pará, considerando o enorme potencial do estado, se tratando de matéria prima e cultura. É um trabalho
pioneiro no Brasil. Para dinamizar a produção no Estado, o polo vem criando uma identidade própria para jóias
na área de design, baseado na herança cultural da região e traduzindo-se em peças finas de qualidade.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### Lendas e Mitos

As lendas e mitos fazem parte do imaginário popular paraense. Enquanto que no interior do Estado o
misticismo é mais arraigado, nas escolas de Belém são assimilados pelas crianças os contos sobre boto, cobra
grande, caipora, açaí, guaraná, matinta perêra, muiraquitã, tambatajá, vitória-régia, uirapuru, peixe-boi, lenda da
lua, lenda dos rios, lenda do sol, mapinguari.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::



## Patrimônio Histórico
### Bairro Cidade Velha

Belém nasceu em torno do então Forte do Presépio, área que logo foi chamada de cidade e, com o
passar do tempo, recebeu o nome de Cidade Velha. A Cidade Velha é o marco da história de Belém, um dos
maiores referenciais do patrimônio histórico e cultural do Pará. Preserva, em parte, a sua arquitetura colonial,
com fachadas de azulejos portugueses, varandas e grades de ferro (Belém é a cidade brasileira que mais
preservou a arquitetura em ferro das construções do século XIX). É nesse antigo bairro que está guardada a
memória dos índios, negros e portugueses, pioneiros do povoamento da cidade. É também onde estão os
principais pontos turísticos de Belém: casarões antigos, museus, palacetes e igrejas em estilo neoclássico e
imperial brasileiro. O bairro guarda infinitas riquezas do império e da Era da Borracha, época de ouro da história
paraense, seja em museus, galerias, arquivo público, ou em sua arquitetura antiga.


O Centro Histórico de Belém (no bairro da Cidade Velha) guarda ainda o circuito Landi de Arquitetura,
que são as obras que o arquiteto italiano Antônio José Landi projetou. O fato de Belém ser uma das capitais
mais arborizadas do Brasil, oferecendo a sombra das copas de milhares de mangueiras que cobrem ruas e
avenidas e amenizam as altas temperaturas, a faz ser conhecida como a “Cidade das Mangueiras”, também um
legado de Landi, pois apesar da espécie não ser natural da região e sim da índia, foi a primeira a ser utilizada na arborização da cidade, trazida por ele em 1786; foram dezenas de mudas que foram plantadas no centro da
cidade.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### Forte do Castelo

Localizado na Praça Frei Caetano Brandão, é um marco na fundação de Belém. Foi a primeira
construção da cidade. Além de fortaleza militar, também valeu como refúgio de uma das facções dos revoltosos
do movimento cabano no início do século XIX. Durante a II Guerra Mundial, serviu de quartel para uma bateria
de artilharia. Canhões originais ainda estão lá para testemunhar os fatos. O forte não manteve a construção
original; foram feitos vários fortes ao longo do tempo, sendo que a última (atual) edificação data de 1721.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### Ver-o-Peso

Localiza-se na região das Docas do Pará, antiga foz do Igarapé do Piri (Boulevard Castilhos França, no
bairro do Comércio). Em 1687, foi solicitada a Portugal uma concessão para tributar as mercadorias que
chegavam a Belém. Deste ato resultou a criação do Mercado Ver-o-Peso, local onde as mercadorias eram
pesadas e taxadas, sendo que a renda resultante desses impostos custeava a Câmara de Belém. Desde aquela
época, os governantes já enfrentavam o eterno dilema de equilibrar despesa e receita, com a primeira,
invariavelmente, sendo maior que a segunda. O Ver-o-Peso é o símbolo cultural e turístico da cidade, um dos
cartões postais mais conhecidos do estado do Pará e até da Região Amazônica; é lugar onde se encontra uma
amostra do universo de variedade da cultura paraense. É lá que a população começa o dia, comprando e
vendendo mercadorias das mais variadas espécies, como peixes e frutas, plantas ornamentais, raízes,
artesanato e dezenas de ervas medicinais, usadas para o preparo de chás, banhos e defumações, temperos etc.
O intenso movimento dos barcos e o “vai e vem” das pessoas emprestam um belíssimo colorido à paisagem, já
bastante atraente pela variedade de produtos expostos à venda. Tombado pelo Patrimônio Histórico Nacional,
está sendo avaliado pela UNESCO para ser transformado em Patrimônio Cultural da Humanidade.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### Igrejas

A expansão da Cidade de Belém muito se deve às igrejas, conventos e capelas; aos seus arredores,
verificava-se o agrupamento de colonos que, com sua religiosidade, procuravam moradias próximas às casas de
Deus.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Catedral Metropolitana de Belém ou Igreja da Sé

A primeira Capela dedicada ao culto católico em Belém foi construída no Forte do Presépio em 1616 e
dedicada a Nossa Senhora das Graças. Com o tempo, virou ruína. A saída foi construir outra igreja, só que mais
bem apropriada e resistente. O lugar escolhido foi a praça em frente ao Forte (Praça Frei Caetano Brandão).
Apesar da intenção, a igreja durou pouco tempo, pois era de pilão e palha. Foi substituída, mas por outra do
mesmo material. Em 13 de dezembro de 1720, com a constituição do Bispado do Pará, a Matriz (até então Igreja de Nossa Senhora das Graças), ganhou direitos e honras de Sé Episcopal. Foi D. João V, Rei de Portugal, quem
ordenou que no mesmo local fosse erguida uma catedral, com muita magnificência e grandeza.

Em 03 de maio de 1748, o Bispo D. Frei Guilherme de São José lançou a pedra fundamental da
Catedral Metropolitana de Belém ou igreja da Sé, que foi reconstruída pelo arquiteto Antônio Landi, em estilo
neoclássico e barroco colonial. Em 23 de dezembro de 1755, D. Miguel de Bulhões inaugurou o presbitério da
Catedral, que foi concluído em 08 de setembro de 1771. Entre as belezas da Sé, destacam-se as pinturas na
abóbada e tela dos artistas italianos Domenico De Angelis e Giusepe Capranesi, produzidas no século XIX,
quando a Igreja passou por uma ampla reforma. Outro destaque é o grande órgão CavailléColl, inaugurado em
primeira edição no dia 09 de setembro de 1882, pelos organeiros e organistas franceses Veerckamp e Moor. A
Catedral possui ainda o Ossuário ou Capela das Almas (onde são sepultados fiéis da igreja católica), a
Residência Paroquial e a Sacristia dos Cônegos. A Catedral é ponto de saída da procissão do Círio de Nossa
Senhora de Nazaré.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Santo Alexandre

Localizada na Praça Frei Caetano Brandão, na Cidade Velha, teve sua construção iniciada no século
XVII, 1635, por religiosos da Companhia de Jesus, quando era apenas uma simples capela de taipa, com
cobertura de telha e chamava-se igreja de São Francisco Xavier. O atual templo da igreja de Santo Alexandre,
considerada a mais barroca de nossas igrejas, foi construído entre os anos de 1718 e 1719 e representa parte
da memória cultural paraense. É inspirado nos principais templos jesuíticos do Brasil e da Europa. A colaboração
indígena imprimiu à fachada do templo um estilo reconhecidamente amazônico. Em 1999, a igreja e o antigo
Arcebispado de Belém (Palácio Arquiepiscopal) passaram por uma grande restauração, compondo o Conjunto
Arquitetônico onde funciona o Museu de Arte Sacra do Pará, um belíssimo espaço que resgata valores estéticos,
históricos e culturais do estado. Ao lado de um anexo, esses dois prédios, tombados pelo instituto do Patrimônio
Histórico e Artístico Nacional (IPHAN), formam o Complexo Feliz Lusitânia.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Nossa Senhora do Carmo

Localizada na Praça do Carmo, foi fundada no século XVII (1627) pela Ordem dos Carmelitas Calçados
da Capitania e reconstruída em 1716. A igreja conta com o estilo neoclássico em sua fachada e o barroco em
seu interior. Seu altar é de prata. Integra o Conjunto Arquitetônico que inclui o antigo Convento dos Carmelitas. A
partir de 1766, Landi atuou na igreja do Carmo e também na capela anexa, Ordem Terceira do Carmo. É uma
das mais importantes de Belém, pelo seu valor histórico e artístico, tendo servido como ponto estratégico para a
tropa imperial durante a Cabanagem.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Capela de São João Batista

Está localizada na Praça República do Líbano, na Cidade Velha. A igreja primitiva foi construída em
1622, em taipa e coberta de palha, tendo servido de presídio ao jesuíta Pe. Antonio Vieira, em função de sua
dedicação à causa indígena. Foi demolida em 1686, quando outra igreja, também em taipa, foi levantada no
mesmo local. Tornou-se matriz em 1714 e, em 1721, passou a ser Catedral de Belém até 1755. A partir de 1772,
teve início a construção da atual igreja, projetada pelo arquiteto Antonio Landi, sendo inaugurada em 1777.
Ainda que por fora seja quadrada, seu interior apresenta forma octogonal (com elegante cúpula sobre a nave de
rara beleza), o que era bastante incomum na arquitetura colonial brasileira. Além dos aspectos arquitetônicos, a
capela tem aspectos preciosos de arte decorativa em seu interior. As pinturas do altar principal e das laterais são
feitas em técnica que imita volumes e relevos. Foi restaurada em 1996, pelo IPHAN. Nesta igreja, encontraram-
se pinturas feitas por Landi que estavam escondidas por camadas de tinta branca e foram recuperadas em 1997.
A Capela de São João Batista foi considerada pelo antigo diretor do Museu do Louvre, Germain Bazin, “uma jóia
da arquitetura barroca”.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Nossa Senhora das Mercês

Localizada na Praça das Mercês, no Bairro do Comércio, foi construída pelos frades mercedários. Seu
traçado original é do século XVII (1640). Inicialmente, era de taipa e pilão, coberta de palha. Em 1753, um novo
templo foi levantado a partir do projeto do arquiteto italiano Antônio Landi, com substanciais alterações.
Apresenta diversos estilos, predominando o barroco. A Igreja das Mercês é a única em Belém que possui a
fronteira em perfil convexo. A igreja faz parte de um conjunto arquitetônico que inclui o Convento dos
Mercedários e a antiga Alfândega. O convento foi construído pelos frades mercedários ao lado da igreja. Ambos
ficaram em poder desses frades até 1794, quando o rei de Portugal os expulsou do Pará, confiscou e incorporou
seus bens à coroa lusa. A igreja passou à Irmandade Militar do Santo Cristo. No antigo convento, houve a
instalação da Alfândega e da Casa do Parque. Lá também funcionaram a Casa da Praça do Comércio, a
Recebedoria Provincial, o 16o Batalhão de Caçadores, o Arsenal de Guerra, o Quinto Corpo de Artilharia e o
Correio.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Nossa Senhora de Sant’Ana da Campina

Localizada na Praça Maranhão, no Comércio, foi construída em 1761 e reconstruída em 1855, em estilo
renascentista, é também projeto do arquiteto Landi, cujo corpo foi enterrado em sua nave, em local não
identificado. Pelo traçado original, tinha a forma de uma cruz grega coroada de uma cúpula e lanterna.
Primitivamente, segundo Baena, possuía vários painéis no altar do sacramento e no das almas. Em 1839, com a
derrubada de duas colunas construídas lateralmente, foram levantadas duas torres, conforme se vê nos dias de
hoje. Em 1855, sofreu várias reformas, quase uma reconstrução. Conserva ainda as belas pinturas de Pedro
Alexandre de Carvalho, feitas no século XVIII. Outra obra de arte ali encontrada é a imagem de São Pedro,
fundida em bronze.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Capela do Senhor Bom Jesus dos Passos (Capela dos Pombos)

Localiza-se no Comércio. O senhor de engenho, Ambrósio Henrique da Silva Pombo, ao construir sua
residência em Belém, dotou-a de uma capela oferecida ao Senhor dos Passos, construída em 1790, onde ele,
sua família, seus amigos e seus escravos assistiam o Santo Sacrifício da Missa e a outros ofícios da religião. A capela possui fachada branca, de linhas neoclássicas, e sutis motivos barrocos de ornamentação. Nos tempos
imperiais, a capela desempenhou papel relevante na história eclesiástica da cidade: os bispos designados para
a diocese paraense desembarcavam do vapor e vinham diretamente ao Santuário do Senhor dos Passos, a fim
de se paramentarem. Depois, então, é que se dirigiam aos cerimoniais de posse na Catedral. Sendo propriedade
particular, só abre ao público uma vez por ano, no domingo da Páscoa, quando chega a grande procissão de
Nosso Senhor dos Passos, onde é realizado o quinto passo.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Nossa Senhora do Rosário dos Homens Pretos da Campina

Localiza-se no bairro da Campina. Sua primeira construção, feita de taipa-de-pilão, data do final do
século XVII. Mas foi em meados do século XVIII, com a chegada do arquiteto Antônio Landi, que a igreja se
tornou um Templo, pois além de fazer a planta, ele contribuiu financeiramente para as obras.
Ao descrever essa igreja, Ernesto Cruz lembra que nela são vistos restos da influência colonial: as
urupemas das janelas, as lajotas de barro vermelho que formam o piso dos corredores laterais e os altares
produzidos por mãos hábeis.

Entre as obras de arte ali existentes, salienta-se uma grande tela representando a Virgem Maria, que
pode ser vista no batistério, e os ricos castiçais e lanternas de prata maciças, tudo frutos de quase duzentos
anos de trabalho dos humildes escravos da Belém Colonial e Imperial.
Entre as pessoas sepultadas naquela igreja, está o líder cabano Antônio Vinagre, morto na tarde de 14
de agosto de 1835, no Largo das Mercês, quando os revolucionários invadiram, pela segunda vez, a capital
paraense.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja e Convento de Santo Antônio

O início das obras do convento de Santo Antônio data do ano de 1626, sob a responsabilidade dos
capuchos da Província de Santo Antônio, por sinal, os primeiros religiosos que vieram ao Pará. E, pela ordem
cronológica de construção, o segundo convento a ser erguido em Belém (o primeiro foi o do Carmo).

Em 1736, estando o edifício original arruinado, um novo convento e uma nova igreja começaram a ser
levantados. A 13 de junho de 1743, foram festivamente inaugurados.

Naquele tempo, as águas da baía do Guajará iam até as paredes do convento. Para protegê-las, os
capuchos começaram a construir um cais de proteção, somente concluído em 1782, já pelo Senado da Câmara
de Belém, que o prolongou até uma rampa, que era conhecida por Sacramenta.

Após a Cabanagem, o governo instalou no antigo convento uma escola de ensino misto. No mesmo
período, ali também funcionou uma escola gratuita de gramática latina, dirigida pelo frei Antônio de Santa
Teresa. Depois, serviu como quartel da polícia (1846). Anos depois, foi o Seminário Pequeno de Belém. Por fim,
um Asilo de Órfãs Desvalidas, mantido pelo governo e entregue à direção das irmãs Dorotéias, em 1878. E o
Asilo de Santo Antônio transformou-se, nos tempos modernos, no tradicional colégio de mesmo nome.


Diz-nos Ernesto Cruz que “a Igreja é ornada de azulejos que datam do século XVIII. Na capela-mor no
corredor e na sacristia podem ser vistas e admiradas as artísticas faianças, tão antigas como as do convento de
São Francisco, da Baía. Também as paredes da torre são em parte ataviadas de azulejos. Não existe, contudo,
indicação que esclareça o autor da pintura das louças e da olaria onde foram fabricadas”.
Muito bonito também é o forro da sacristia, pintado em 1774. Encontra-se perfeitamente conservado,
como um testemunho vivo do bom gosto dos artistas do passado.


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

#### Igreja de Nossa Senhora de Nazaré

A primitiva capela de Nossa Senhora de Nazaré foi levantada por Agostinho Antônio, em louvor à
Virgem. Em 1799, o governador D. Francisco de Souza Coutinho, devoto da Virgem e criador do Círio em 1793,
determinou que nova ermida fosse ali construída, de pedra e cal.

A 12 de setembro de 1852, era solenemente lançada a pedra fundamental da 3a igreja. O autor da
planta foi José Joaquim da Cunha.

Por fim, em 1909 (na fase áurea da borracha), teve início a construção do 4o templo, muito belo,
suntuoso, como se vê nos dias de hoje, que abriga a imagem da Santa que foi encontrada pelo caboclo
paraense, Plácido de Souza. Autorizou a obra o visitador dos Barnabitas, padre Loniz Zota. Em 1923, era a
igreja elevada à categoria de Basílica (decreto da Santa Sé, de 19 de julho, assinado pelo secretário do Vaticano
padre Card Gasparri). O projeto original pertence ao arquiteto Gino Coppode e ao engenheiro Pedrasso, ambos
italianos, e foi inspirado na Basílica de São Paulo, em Roma.

A fachada possui uma arquitetura eclética, mas não foge às linhas clássicas - Romanas. O interior é
todo de mármore carrara e ouro, exceto o forro, em madeira de lei paraense. Em suas colunas internas, granito
rosa importado de Baveno, Itália. No altar-mor, um nicho rodeado de anjos de mármore para guardar a imagem
original da Virgem de Nazaré. Nas suas torres laterais, estão os mais famosos carrilhões eletrônicos do Brasil.
Possui 53 vitrais coloridos que retratam passagens bíblicas. Foi tombada pelo patrimônio Histórico e Cultural em
1992.

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


#### Igreja da Santíssima Trindade

O português José Antônio Abranches, que morava perto da Aldeia (atual rua Bailique), não muito
distante da Estrada das Mongubeiras (Almirante Tamandaré), era fervoroso devoto da Santíssima Trindade. Ele
idealizou construir uma igreja. Para isso, encaminhou um requerimento ao Senado da Câmara solicitando a
doação de um terreno, no que foi atendido. A área doada localizava-se na parte da cidade outrora encharcada
pelas águas do igarapé do Piri, que tinha sido aterrada.

A construção da igreja teve início em 1802. O seu idealizador morreu, mas seus irmãos levaram a obra
avante. Em 1841, era aberta ao culto, com o altar-mor e quatro arcos nas paredes laterais, “indicando os lugares
em que, no futuro, se deveria edificar mais quatro altares. Elevada à categoria de freguesia em 1840, três anos
após reabria, melhorada interna e externamente. Em 1894, estando o prédio bastante arruinado, foi fechado ao
culto. A 14 de outubro do mesmo ano, ocorreu o ato solene da bênção e colocação da primeira pedra da capela-
mor, feita pelo monsenhor José Gregório Coelho”.

Sucedeu-o na direção da paróquia e no desvelo para com a construção da nova igreja, o monsenhor
Hermenegildo Perdigão e o padre Miguel Inácio. A construção foi dada como concluída em 1942. O monsenhor
Antônio Cunha fez a bênção solene do templo e das imagens.





::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
